#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely
#In between each iteration of the loop, add a sleep 2
i=0
while [ $i -lt 10 ]
	do
		sleep 2
		echo "To infinity and beyond"
done
