#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
i=1
j=4
k=8
while ((i <= 10))
	do
		if [ $i -le $j ]
			then
			echo "bad luck"
		elif [ $i -le $k ]
			then
			echo "good luck"
		else
			echo "Best school"
		fi
		((i++))
done
